- name: Installing Docker, creating Container and installing Webserver inside the same with the Git Installed
  hosts: localhost
  connection: local/apache2/htdocs
  gather_facts: no
 
  tasks: 
   - name: Configuring Docker Repository
     yum_repository:
       name: Docker
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
       gpgcheck: yes
       gpgkey: "https://download.docker.com/linux/centos/gpg" 
     register: x

   - name: Checking Configuration Status
     debug:
       var: x.failed

   - name: Installing Docker
     package:
       name: "docker-ce"
       state: present
     register: y

   - name: Checking Install Status
     debug:
       var: y.failed

   - name: Starting Docker Daemon
     service:
       name: docker
       state: started
       enabled: yes
     when: y.failed == false

   - name: Install
     command: "pip install docker-py"
   
   - name: Configuting Docker Network for Webserver
     docker_network:
       name: webserver_network
       driver: bridge
       ipam_config:
         - subnet: 172.168.10.0/30

   - name: Pull a Docker Image
     docker_image: 
        name: httpd
        tag: latest
        source: pull
     register: z
   - name: Checking Pull Status
     debug: 
       var: z

   - name: Creating a Persistent Volume Dir
     file:
       path: "/root/pv"
       state: directory

   - name: Copying the HTML code in the Directory
     copy: 
       src: "home/gnanasekar/Desktop/index.html"
       dest: "/root/pv"

   - name: Launching an HTTPD Container
     when: z.failed == false
     docker_container:
       name: apache-server-container
       image: httpd
       state: started
       networks:
         - name: webserver_network
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
       volumes: 
         - /root/pv:/usr/local/apache2/htdocs
       command:
         /bin/bash -c "apt-get update && apt-get install -y git && exec httpd -DFOREGROUND"
